[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
        certFile = "/certs/seedbox.pem"
        keyFile = "/certs/seedbox.key"

[http.middlewares]
  [http.middlewares.ssl-redirect.headers]
    SSLRedirect = true